# This docker-compose is for local development / test only

version: '3.6'

services:
  # API
  api:
    image: docker.pkg.github.com/landazuripaul/nest-react/nest-react-api:latest
    volumes:
      - ./packages/api/env/local.env:/usr/src/nest-react/packages/api/env/local.env
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=local

  # Frontend
  frontend:
    image: docker.pkg.github.com/landazuripaul/nest-react/nest-react-frontend:latest
    ports:
      - '8000:80'
